# Generated by Django 3.2.11 on 2022-04-19 10:17

import applicationbase.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicationbase', '0002_auto_20220418_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliactions',
            name='calcucalted',
            field=models.BooleanField(default=False, verbose_name='Деньги сданы'),
        ),
        migrations.AlterField(
            model_name='appliactions',
            name='img_door_closer',
            field=models.ImageField(blank=True, null=True, upload_to=applicationbase.utilities.get_timestamp_path, verbose_name='Фото доводчика'),
        ),
    ]
