# Generated by Django 3.2.11 on 2022-04-19 10:28

import applicationbase.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicationbase', '0003_auto_20220419_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_door_closer', models.ImageField(upload_to=applicationbase.utilities.get_timestamp_path, verbose_name='Фото доводичка')),
                ('Appliactions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicationbase.appliactions', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Доп фото',
                'verbose_name_plural': 'Доп фото доводчика',
            },
        ),
    ]
