# Generated by Django 3.2.11 on 2022-05-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicationbase', '0007_commnet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commnet',
            new_name='Commet',
        ),
    ]
